import initTabNav from "./modules/tab-nav.js";
import initAccordionNav from "./modules/accordion-nav.js";
import initSmoothScroll from "./modules/smooth-scroll.js";
import initScrollAnimation from "./modules/scroll-animation.js";
import initModal from "./modules/modal.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initTimeOperation from "./modules/time-operation.js";
import initFetchAnimals from "./modules/fetch-animals.js";
initTabNav();
initAccordionNav();
initSmoothScroll();
initScrollAnimation();
initModal();
initDropdownMenu();
initTimeOperation();
initFetchAnimals();
